version: '3.9'

services:
    db:
        image: postgres
        volumes:
        - ./data/db:/var/lib/postgresql/dat
        extra_hosts:
        - "host.docker.internal:host-gateway"

    web:
        build: .
        command: python /address_book_main/address_book_main/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/address_book_main
        ports:
        - 8000:8000
        depends_on:
        - db
        extra_hosts:
        - "host.docker.internal:host-gateway"


volumes:
  postgres_data:
