version: '3'

services:
    python:
        image: python:3.10
        volumes:
            - ./address_book_main:/address_book_main
        ports:
            - 8000:8000
        command: bash -c "cd ./address_book_main && pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"